In [ ]:
#Numpy Assignment
'''1. What is a Python library? Why do we use Python libraries?
Ans :  Python library is simply a collection of codes or modules of codes that we can use in a program for specific operations and for data analysis.'''

In [ ]:
'''2. What is the ^ifference between Numpy array and List?
1. it is faster than list
2. It stores homogenous data an d list stores hetrogenous data
3. it can crete N-dimensional array using Numpy.array() 
4. It is used for scientific-computation 
5. it stores in sequential manner and list stores data in random manner

In [13]:
'''3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr
    

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
np.size(arr)

12

In [15]:
np.shape(arr)

(3, 4)

In [5]:
arr.ndim

2

In [16]:
'''4. Write python code to access the first row of the following array?'''
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[0]

array([1, 2, 3, 4])

In [17]:
'''5. How do you access the element at the third row and fourth column from the given numpy array?'''
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[2][3]

12

In [18]:
'''6. Write code to extract all odd-indexed elements from the given numpy array?'''
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[1,[1,3]]

array([6, 8])

In [45]:
'''7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1 ?'''
import random
arr = np.random.rand(3,3)
arr

array([[0.62821458, 0.8958151 , 0.73862402],
       [0.9766178 , 0.70545725, 0.04514112],
       [0.83125043, 0.24935643, 0.20486175]])

In [ ]:
'''8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?'''
'''Ans : np.random.rand is produced  numbers for uniform distribution  and np.random.randn for normal doistribution

In [60]:
'''9. Write co^e to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a= np.expand_dims(arr,axis =0)
a.ndim
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [61]:
np.shape(a)

(1, 3, 4)

In [ ]:
'''10.10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [63]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a=np.transpose(arr)
a

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
'''11. Consi^er the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python1
1 Index wise multiplicationA1'
2. Matix multiplicatio'
+ Add both the maticK
-+ Subtact matix B om 
+ Diide Matix B by A'''

In [72]:
A2=[[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
A2= np.array(A2)
B2= [[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]]
B2= np.array(B2)
A2 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
B2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
np.shape(A2)

(3, 4)

In [77]:
np.shape(B2)

(3, 4)

In [79]:
A2 * B2 # index wise multiplication

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [84]:
A3= np.reshape(B2,(4,3)) #     Matrix multiplication 


In [85]:
A2 @ A3

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])

In [86]:
A2 + B2                           # ADD the matrix

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [87]:
A2 / B2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [89]:
A2 -B2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [90]:
'''12. Which function in Numpy can be used to swap the byte order of an array?'''
'''Ans :np.byteswap()
#byte representation of the data

AttributeError: module 'numpy' has no attribute 'byteswap'

In [91]:
'''13. What is the significance of the np.linalg.inv function?
Ans :It will calculate the inverse of the matrix 

SyntaxError: incomplete input (420265349.py, line 1)

In [ ]:
'''14. What does the np.reshape function do, and how is it used?
Ans : It will change the shape of an array  without changing its data of an array.. when u want to change the shape ,the product of the dimension of the new shape will be equal to the product of the old dimension 

In [ ]:
'''15 what id broadcastiong in numpy'''
Ans : Broadcasting will do some  operation on each of the element in the array  and it will broadcast  but there is some constraint that the smaller array is broadcast to larger array 